### ISSUE TITLE
Modify PackingIterator to return the biggest bin

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#114]
As discussed in [this email thread](https://lists.apache.org/thread.html/5855b3f6ebff65d3f2a4826aeb93984729f3b6ec569c3eb4abea47eb@%3Cdev.iceberg.apache.org%3E), we should modify `PackingIterator` to return the biggest bin instead of the first one when the number of bins exceeds `lookback`.

**Comment by rominparekh** [comment]
I'll attempt a crack at this!

**Comment by rominparekh** [comment]
@aokolnychyi : I'm unable to close this issue. Can you help close it given the corresponding is merged? Thank you.

**Comment by aokolnychyi** [comment]
@rominparekh sorry, I was away for a few days. Thanks for working on this!
