### ISSUE TITLE
Apply license gradle plugin

### ISSUE THREAD

**Issue by rdsr** [apache/incubator-iceberg#124]
We should add the license gradle plugin - https://github.com/hierynomus/license-gradle-plugin , which would automatically check that all files have license headers

**Comment by mccheah** [comment]
We propose this as a subset of gradle-baseline in https://github.com/apache/incubator-iceberg/pull/28. I don't see why we would need a separate license Gradle plugin if we can satisfy the same requirements using Checkstyle as Baseline does - thoughts?

**Comment by rdsr** [comment]
@mccheah makes sense. I should have looked into the previous ticket more thoroughly. I'll close this
