### ISSUE TITLE
ParquetMetrics computes wrong lower/upper bounds for small decimals

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#125]
It seems `ParquetMetrics` computes wrong lower/upper bounds for decimals that are represented as int64 in Parquet. Consequently, Iceberg can filter out data files that contain relevant data for a query.

Create a Parquet file with one row:
```
    Schema schema = new Schema(
      optional(1, "decimalCol", Types.DecimalType.of(10, 2))
    );

    GenericData.Record record = new GenericData.Record(AvroSchemaUtil.convert(schema.asStruct()));
    record.put(0, new BigDecimal("3.50"));

    File parquetFile = newParquetFile();
    try (FileAppender<GenericData.Record> writer = Parquet.write(localOutput(parquetFile))
        .schema(schema)
        .build()) {
      writer.add(record);
    }
```

Explore this file using parquet-tools (min/max values are correct):
```
file schema: table 
--------------------------------------------------------------------------------
decimalCol:  OPTIONAL INT64 O:DECIMAL R:0 D:1

row group 1: RC:1 TS:75 OFFSET:4 
--------------------------------------------------------------------------------
decimalCol:   INT64 GZIP DO:0 FPO:4 SZ:91/75/0.82 VC:1 ENC:BIT_PACKED,PLAIN,RLE ST:[min: 3.50, max: 3.50, num_nulls: 0]
```
Create an Iceberg table:
```
    String tableLocation = newTableLocation();
    Configuration conf = new Configuration();
    HadoopTables hadoopTables = new HadoopTables(conf);
    Table table = hadoopTables.create(schema, tableLocation);
```

Append the Parquet file to the table:
```
    DataFile dataFile = DataFiles.builder(PartitionSpec.unpartitioned())
      .withFileSizeInBytes(parquetFile.length())
      .withPath(parquetFile.toString())
      .withMetrics(fromInputFile(localInput(parquetFile)))
      .build();

    table.newAppend().appendFile(dataFile).commit();
```

Query the table via Spark:
```
    Dataset<Row> df = spark.read()
      .format("iceberg")
      .load(tableLocation);

    df.show();
    +----------+
    |decimalCol|
    +----------+
    |      3.50|
    +----------+
    df.where("decimalCol = 3.50").show();
    +----------+
    |decimalCol|
    +----------+
    +----------+
    df.where("decimalCol = CAST(3.50 AS DECIMAL(10,2))").show();
    +----------+
    |decimalCol|
    +----------+
    +----------+
```

This happens because `ParquetMetrics` uses `ParquetConversions$fromParquetPrimitive`, which assumes that decimals are always represented as binary.

In this particular case, `org.apache.parquet.column.statistics.Statistics$genericGetMin` will return a long value.

**Comment by aokolnychyi** [comment]
@rdblue while testing a fix for #78, I saw that lower/upper bound for small decimals are not computed correctly. Did I miss smth in my analysis above?

**Comment by rdblue** [comment]
@aokolnychyi, looks correct to me. Do you have time to submit a fix? Sounds like you're already familiar with what is broken.

**Comment by aokolnychyi** [comment]
Due to the open source approval within my company, the fix will be upstream by the end of next week. If it is an acceptable timeframe for this bug, I'll go ahead and fix it. If we need it earlier, someone else will have to do it and I can help to review.

**Comment by rdblue** [comment]
Sounds good to me!
