### ISSUE TITLE
[Baseline] Apply Baseline to iceberg-data

### ISSUE THREAD

**Issue by mccheah** [apache/incubator-iceberg#156]
Use the Baseline plugin to add linting for iceberg-data. Part of the greater effort to apply Baseline across the project. (Issues are being created individually so that contributors can claim assignment for each of these).

**Comment by rdsr** [comment]
I can cover this. Thanks @mccheah

**Comment by aokolnychyi** [comment]
@rdsr @mccheah @rdblue Shall we close this one?

**Comment by Fokko** [comment]
@rdsr @mccheah @rdblue I think we can close this one: https://github.com/apache/incubator-iceberg/blob/master/build.gradle#L167

**Comment by rdblue** [comment]
Fixed by #198.
