### ISSUE TITLE
[Baseline] Apply Baseline to iceberg-hive

### ISSUE THREAD

**Issue by mccheah** [apache/incubator-iceberg#157]
Use the Baseline plugin to add linting for iceberg-hive. Part of the greater effort to apply Baseline across the project. (Issues are being created individually so that contributors can claim assignment for each of these).

**Comment by aokolnychyi** [comment]
I've spent quite some time on this module as well, so I can cover it pretty quickly in addition to spark.

**Comment by aokolnychyi** [comment]
This one is done and is awaiting an open source approval.
