### ISSUE TITLE
[Baseline] Apply Baseline to iceberg-orc

### ISSUE THREAD

**Issue by mccheah** [apache/incubator-iceberg#158]
Use the Baseline plugin to add linting for iceberg-orc. Part of the greater effort to apply Baseline across the project. (Issues are being created individually so that contributors can claim assignment for each of these).

**Comment by aokolnychyi** [comment]
@rdsr @mccheah @rdblue Shall we close this one?

**Comment by rdsr** [comment]
+1

**Comment by rdblue** [comment]
Closing because it's done. Thanks @rdsr!
