### ISSUE TITLE
[Baseline] Apply Baseline to iceberg-spark

### ISSUE THREAD

**Issue by mccheah** [apache/incubator-iceberg#161]
Use the Baseline plugin to add linting for iceberg-spark. Part of the greater effort to apply Baseline across the project. (Issues are being created individually so that contributors can claim assignment for each of these).

**Comment by aokolnychyi** [comment]
I would be glad to work on this.

**Comment by aokolnychyi** [comment]
I will start working on this in 2 days

**Comment by aokolnychyi** [comment]
I've completed the Java part locally. What do we do with Scala?
@rdblue @mccheah Which `scalastyle_config.xml` do we want to use? Spark?

**Comment by mccheah** [comment]
Baseline has a `scalastyle` plugin: `com.palantir.baseline-scalastyle`. Can we apply that plugin and see how it lints the existing code?

**Comment by aokolnychyi** [comment]
@mccheah Baseline uses `org.github.ngbinh.scalastyle` and sets the config location to `project/scalastyle_config.xml`. I think having the config under `.baseline/scalastyle` would be better.

How do I overwrite this in Baseline? I've tried multiple approaches but they didn't work for me.
I could configure `org.github.ngbinh.scalastyle` if applied directly.

**Comment by mccheah** [comment]
Unfortunately I don't think there is such a way, looking at the Baseline source code. I think putting the configuration under `project/scalastyle_config.xml` is fine.
