### ISSUE TITLE
Upgrade Guava and don't use deprecated methods like Objects#ToStringHelper

### ISSUE THREAD

**Issue by mccheah** [apache/incubator-iceberg#162]
Our Guava dependency is pretty old right now. When we bring in Iceberg as a dependency, we hit `NoSuchMethodError`s when calling the `Objects#toStringHelper` method, which was removed in later versions of Guava. It's been replaced by `MoreObjects#toStringHelper`.

There's two matters to consider here:
- Should we bump Guava? We're using 23.6.1: https://github.com/palantir/incubator-iceberg/pull/8
- Let's minimize our use of Guava's deprecated APIs. We can start with `toStringHelper` and perhaps add linting rules to find others.

**Comment by aokolnychyi** [comment]
I am +1 on this. @rdblue what do you think?

**Comment by rdblue** [comment]
I definitely agree about minimizing the use of deprecated APIs that we know will be a problem for people that upgrade.

My concern about upgrading the version we use is that it could cause problems downstream. Do we expect everyone to shade guava? Also, now that we are using Caffeine, should we consider moving off of Guava?

I think we mainly use Guava for 4 things:
* Caches - replaced by Caffeine
* Iterables and Iterators
* Preconditions - easily replaced
* Maps, Lists, etc. for new and immutable containers

If we can find a good alternative for iterables/iterators that hopefully doesn't require too much of the streams API, maybe we should consider using that. We could also build alternatives of those for Iceberg; we already have a fair number of them in `CloseableIterable`.

**Comment by rdsr** [comment]
> My concern about upgrading the version we use is that it could cause problems downstream

Could we shade our Guava dependency in our artifacts?  We'd have to make sure that guava is bundled in our artifacts and shaded and is not fetched transitively, whereas the rest of the dependencies can be fetched transitively.  Shadow plugins allows us to do this. This could be some work and could change how our artifacts are fetched . Users would have to rely on the different classifier or configuration for the artifacts for example.

**Comment by rdblue** [comment]
We could do something similar to what Avro and Parquet do -- build a shaded Jar and rewrite everything to depend on that. I'd rather not do that if we can cleanly move off of Guava, though. Does anyone agree with the idea of trying to move off?

**Comment by aokolnychyi** [comment]
Do you mean building alternatives ourselves?

**Comment by rdblue** [comment]
For preconditions and iterators/iterables, we would probably build alternatives. A lot of those are already implemented in `CloseableIterables`. Preconditions are easy to add, too.

The main annoyance is the container types, including immutable variants. Is there an alternative for those?

**Comment by mccheah** [comment]
To be clear I think it's appropriate to use Guava's APIs that are marked as stable, not deprecated, and not experimental / beta. Guava should be committed to API stability and thus it shouldn't be a problem if the Guava dependency is swapped from under the hood.

The issue is that we were using deprecated methods that were removed.

I wonder if we can add a linting check for this.

**Comment by rdblue** [comment]
After a little searching, I don't see good alternatives for the immutable collections. I think we should move forward with upgrading Guava and not using deprecated methods.

**Comment by SurenNihalani** [comment]
+1. 

I'll get a PR going for this (the intellij support for iceberg is buggy for this project. It picks up an older version of guava and doesn't find symbol for toStringHelper)

**Comment by rdblue** [comment]
Thank you @SurenNihalani!
