### ISSUE TITLE
All compile scope dependencies should be explicitly declared 

### ISSUE THREAD

**Issue by vrozov** [apache/incubator-iceberg#175]

**Comment by vrozov** [comment]
iceberg-parquet uses classes from `commons-io` without declaring `commons-io` as a compile-time dependency relying on transitive dependency from `hadoop-common`.

**Comment by manishmalhotrawork** [comment]
@vrozov 
[https://github.com/apache/incubator-iceberg/issues/174](174)

**Comment by vrozov** [comment]
@manishmalhotrawork The issue is more generic than just adding the dependency on `commons-io`. It is necessary to enable check during the build that all modules declare used dependencies and do not rely on transitive dependencies.

**Comment by rdblue** [comment]
We recently cleaned up dependencies in #250 and #230 fixed the commons-io problem. Feel free to reopen this if there are more changes to be done.

**Comment by vrozov** [comment]
@rdblue Please reopen as the issue is not fixed by #250 and/or #230. To confirm, please use `checkImplicitDependencies` task:
```
Execution failed for task ':iceberg-core:checkImplicitDependencies'.
> Found 2 implicit dependencies - consider adding the following explicit dependencies to 'core/build.gradle', or avoid using classes from these jars:
      dependencies {
          implementation 'io.netty:netty-all'
          implementation 'org.apache.hadoop:hadoop-common'
      }
```

**Comment by rdblue** [comment]
@vrozov, where are these used? I'm not aware of anything that would require Netty.

**Comment by vrozov** [comment]
@rdblue See https://github.com/apache/incubator-iceberg/blob/master/core/src/main/java/org/apache/iceberg/RemoveSnapshots.java#L25. It is exactly the problem that #175 supposed to address: accidental usage of transitive dependencies. It also looks that dependency on hadoop-client is excessive and dependency on hadoop-common will be sufficient.

**Comment by vrozov** [comment]
Please note that due to https://github.com/palantir/gradle-baseline/issues/567 `com.palantir.baseline-exact-dependencies` can't be used to check for implicit dependencies.
