### ISSUE TITLE
Use Iceberg tables as sinks for Spark Structured Streaming

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#178]
Users should be able to use Iceberg tables as sinks for Spark structured streaming. 

Spark provides `queryId` and `epochId` to all sinks, which must ensure that all writes are idempotent. Spark might try to commit the same batch multiple times. So, we need to know the latest committed `epochId` for every query. One way to do so is by persisting `queryId` and `epochId` in the snapshot summary. On writes, we can simply iterate through the snapshots and check the latest committed `epochId` for a given query to make writes idempotent.

**Comment by aokolnychyi** [comment]
I'll plan to work on this in the near future

**Comment by aokolnychyi** [comment]
@rdblue what would be the best way to store smth in the snapshot summary? How do you do this for Flink? For example, we interact only with `AppendFiles` API while appending new files.

**Comment by rdblue** [comment]
We added a `set` method, looks like I forgot to open a PR for it. I'll do that shortly.

**Comment by aokolnychyi** [comment]
@rdblue great, I'll try to use it for this effort.

**Comment by rdblue** [comment]
See #180.

**Comment by aokolnychyi** [comment]
@rdblue close to what I had locally, worked for me!

It would be also helpful to have access to `TableMetadata` for SS. `Table$snapshots` returns snapshots starting from the first one. To find the latest committed `epochId`, it would make sense to iterate the snapshot lineage backwards starting from the most recent one. In most cases, we would stop after a couple of iterations. `TableMetadata` has enough information. Do we consider it as private API? There is no way to easily retrieve it, right?

**Comment by rdblue** [comment]
We should be able to use the Table API to traverse all of the snapshots. You can get all the snapshots with `table.snapshots` then index by the ID, and traverse using `current.parentId()`.

**Comment by aokolnychyi** [comment]
Yeah, that's what I actually did, was worried about redoing the same work twice. I hope iterating through snapshots won't become a bottleneck in the commit phase.

**Comment by rdblue** [comment]
We could expose the lookup function directly so we don't have to index.

**Comment by aokolnychyi** [comment]
I have a working prototype. How do we want to handle `OutputMode.Complete()` in Structured Streaming? Right now, I am using `OverwriteFiles` to remove all existing files and append new ones.

**Comment by rdblue** [comment]
`OutputMode.Complete` should replace all rows in the table using `OverwriteByExpression` with `true`.

**Comment by aokolnychyi** [comment]
I am using `OverwriteFiles$overwriteByRowFilter` with `Expressions.alwaysTrue()`. Is it what you meant?

**Comment by rdblue** [comment]
@aokolnychyi, sorry for the late reply. Yes, that's what I think it should do.

**Comment by goldentriangle** [comment]
Any ETA for this feature?

**Comment by aokolnychyi** [comment]
It is done and awaiting an open source approval. I hope to get it public in early next week.
