### ISSUE TITLE
`SparkOrcReader#read()` can potentially be optimized

### ISSUE THREAD

**Issue by rdsr** [apache/incubator-iceberg#195]
In  `SparkOrcReader#read` we build a DAG of converters everytime we  call the `read` method.  This  DAG converts an ORC row to Spark InternalRow. This seems like an expensive operation as it traverse the whole row structure. It seems that building of the converters can be taken out of the read method, and done only once. Ideally all it should require is the structure of the row (schema) to figure how how it will convert an ORC row to InternalRow.

@edgarRd do you think this makes sense? I have a rough idea in my mind on how to implement it.  But let me know if you think this could not be possible.

**Comment by edgarRd** [comment]
Yeah, I was aware this part of the code could be optimized. Originally I was thinking to refactor those converters to a set of visitors to convert the ORC row to InternalRow and avoid this building of the DAG of converters. Pretty much this is what is done in the Parquet reader as well.

What did you have in mind?

**Comment by rdsr** [comment]
@edgarRd, here's some rough code which passes the tests. https://github.com/rdsr/incubator-iceberg/commit/0b9bb24add8b25acb526e7179c4d02acef9fdf34 . I still have to verify whether the underlying approach is correct, given that the way I use `UnsafeWriter` in the code is very much different from yours

**Comment by edgarRd** [comment]
@rdsr I think this looks reasonable, essentially these changes avoid storing the `UnsafeWriter` in the converters which allows to create the converters only once. I think this makes sense. 
Would you mind sending a PR for this?

Thanks!

**Comment by rdsr** [comment]
Will do @edgarRd!
