### ISSUE TITLE
iceberg-runtime should not bundle hadoop dependencies

### ISSUE THREAD

**Issue by rdsr** [apache/incubator-iceberg#217]
The dep chain is 
iceberg-runtime -> iceberg-spark -> iceberg-orc -> orc -> hadoop-hdfs

ORC is bringing in an old version (2.2) of hadoop-hdfs

**Comment by rdblue** [comment]
I agree, we should exclude all org.apache.hadoop dependencies in the runtime bundle.

**Comment by rdsr** [comment]
Update description to reflect all hadoop dependencies

**Comment by SurenNihalani** [comment]
I'll grab this
