### ISSUE TITLE
Run checkstyle in CI

### ISSUE THREAD

**Issue by mccheah** [apache/incubator-iceberg#24]
I noticed that it's possible to make a formatting error, such as disorganize imports or change indentation, without `./gradlew check` noticing. This issue proposes adding more rigorous checkstyle and code linting integration to this project.

An idea is to use the [baseline](https://github.com/palantir/gradle-baseline) toolkit, but we can also write the linting configuration by hand.

**Comment by rdblue** [comment]
How are we doing on this? Most modules are running checkstyle, right?

**Comment by mccheah** [comment]
This can probably be superceded by all the individual tasks for Baseline integration.

**Comment by rdblue** [comment]
Thanks! I'll close this.
