### ISSUE TITLE
Convert from Spark table to Iceberg table

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/incubator-iceberg#249]
Currently, Iceberg-spark doesn't have API to convert from a Spark table to iceberg table. User may want to migrate Spark or Hive tables to iceberg tables directly.

**Comment by aokolnychyi** [comment]
[Here](https://lists.apache.org/thread.html/0f55e50fe48c15a55b31277b48e70500c642ea50cf8d6a3f12dfafe4@%3Cdev.iceberg.apache.org%3E) is a relevant email thread on the dev list.

**Comment by chenjunjiedada** [comment]
Hi @aokolnychyi,

I see you mentioned to use a spark job to implement the API, do you mean to use a SparkSession?  I tried some commands in spark-shell and summarized [here](https://github.com/chenjunjiedada/incubator-iceberg/commit/0d607d7f2c1ae0a7630e98e81491359a2c44414c#diff-872bad13b0ca263b20c64cd36768ddc2R284)(Note that it is just a list of commands).

**Comment by chenjunjiedada** [comment]
I spent some time to try this on spark-shell, and now I 'm converting them to code, @rdblue are you working on this as well? I saw you mentioned in another thread.

**Comment by rdblue** [comment]
I haven't yet, feel free to submit a PR!

**Comment by rdblue** [comment]
Fixed by #374
