### ISSUE TITLE
Fix BaseTableScan to include column_sizes in stats columns

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#269]
Right now, `table.newScan().includeColumnStats()` doesn't not include `column_sizes`.

**Comment by manishmalhotrawork** [comment]
@aokolnychyi I can take this up.

**Comment by manishmalhotrawork** [comment]
if its ok with you, and believe would be good for n00b :)

**Comment by aokolnychyi** [comment]
@manishmalhotrawork, sure, go ahead!
