### ISSUE TITLE
Transforming timestamp to date should produce date

### ISSUE THREAD

**Issue by rdblue** [apache/incubator-iceberg#279]
The output type of transforming a timestamp to a date `Transforms.day(Types.TimestampType.withZone()` is an integer, but should be a date. That way, it will be formatted as a date in metadata tables.

When this is updated, we need to validate backward compatibility with existing tables.

**Comment by electrum** [comment]
Should `day` also not support the `date` type, since that would be an identity transform?

**Comment by rdblue** [comment]
You're probably right, although there shouldn't be a difference between the two in practice, once strict projection for dates is added.

**Comment by timmylicheng** [comment]
What are suggested ways to validate backward compatibility?

**Comment by waterlx** [comment]
Hi @rdblue, I am new to iceberg, really appreciate your guidance in advance!
Regarding "The output type of transforming a timestamp to a date Transforms.day(Types.TimestampType.withZone() is an integer, but should be a date", when you say "date", do you refer to "java.util.Date"?
Do you expect Transforms.day(Types.TimestampType.withZone()) returns Transform<T, Date> instead of Transform<T, Integer> ?

**Comment by waterlx** [comment]
Hi @rdblue please correct me if I am wrong:
I am not sure if Transforms.day() is the function to transfer timestamps to date, it is to produce Dates.DAY or Timestamp.DAY (either is Transform) from Types.DateType or Types.TimestampType. By this issue, are you proposing a new method in Transforms which returns Transform<T, java.util.Date> from Types.DateType or Types.TimestampType?

**Comment by electrum** [comment]
Use `java.time.LocalDate`. The older `java.util.Date` actually represents an instant.

**Comment by rdblue** [comment]
@waterlx, the day transform reports that its return type is `IntegerType.get()`, but it should be `DateType.get()`. Both are stored as integers but the transform actually produces the internal value that represents a date: the number of days from the unix epoch.

Changing the return type to date should be safe and would cause engines that support the metadata tables to format the values correctly as dates instead of as integers.

@timmylicheng, the compatibility checks just need to verify that older tables that are partitioned by day can still be read. It's just a matter of writing a table with the current master, making this change and reading with the new library. We don't expect any exceptions while reading or filtering after the update.

**Comment by manishmalhotrawork** [comment]
@rdblue if Im not missing, in this case
`org.apache.iceberg.transforms.Timestamps` will implement `Transform<Long, Date>` and `org.apache.iceberg.transforms.Dates` will implement `Transform<Integer, Date>`.
and internally these classes will use Date object for various transformation like `apply` , `toHumanString`.

@waterlx are you working on this issue ?

**Comment by rdblue** [comment]
@manishmalhotrawork, only the `day` transform should return a date. Years, months, and hours should continue returning ordinals like before.

**Comment by waterlx** [comment]
@rdblue 
> @manishmalhotrawork, only the `day` transform should return a date. Years, months, and hours should continue returning ordinals like before.

so you mean that we are supposed to keep `org.apache.iceberg.transforms.Timestamps` as it is (as `Transform<Long, Integer>`) and keep `org.apache.iceberg.transforms.Dates` as it is (as `Transform<Integer, Integer>`, but only change the output of Transforms.day() to `Transform<T, Date>`? Do I get it right?

@manishmalhotrawork yes, I am working on this issue. But please feel free to go ahead to share your thoughts or upload patches, I am new to iceberg

**Comment by rdblue** [comment]
Sorry for the confusion. I'm talking about the Iceberg date type, `Types.DateType.get()`. The transform implementation is still going to return a Java `Integer` because that's how dates are represented in Iceberg metadata: the number of days from the Unix epoch.

This change would primarily just update `getResultType` and return `DateType.get()` when the granularity is `ChronoUnit.DAYS`. That will cause the partition tuple's field type to be a date, which should also cause the metadata table to display formatted dates instead of the day ordinal in Spark.

**Comment by manishmalhotrawork** [comment]
@rdblue 

> This change would primarily just update getResultType and return DateType.get() when the granularity is ChronoUnit.DAYS. 

this is bit more clear now. thanks  !

so this will change ( if granularity is Days)
1. ` Dates.getResultType `

```
public Type getResultType(Type sourceType) {
    return Types.IntegerType.get();
  }
```

and what about `Timestamps.getResultType` , does it also needs to return `Types.DateType.get()` , as that can also be needed to print datetime in metadata table. ?

**Comment by rdblue** [comment]
Yes, I think both should return `DateType`

**Comment by waterlx** [comment]
Thanks for the clarification, Ryan! I am drafting the patch.

**Comment by manishmalhotrawork** [comment]
@rdblue thanks for the answer.
Just saw messages, before that I also drafted the patch, waiting for internal approval.
@waterlx I can push, and then you can also review? Or otherwise please let me know.

**Comment by manishmalhotrawork** [comment]
@rdblue quick questions.

1. while validating my changes,  didn't see that transfor.getResultType is being used apart from `PartitionSpec.partitionType()`.
can you point me to any other test-case or code path, where its being used can be verified.

( though Im adding test-cases to validate `Days.getResultType()` and `Timestamps.getResultType()`)

2. If we are returning DateType.get for Days why not for Month/Year as well. As for those types as well it will return Integer/day ordinal?

3.
>That will cause the partition tuple's field type to be a date, which should also cause the metadata table to display formatted dates instead of the day ordinal in Spark.

I believe metadata table referenced here is related to #252? Anything specific I need to test/validate if this change impacts the metadata tables?

**Comment by rdblue** [comment]
> can you point me to any other test-case or code path, where [getResultType] is being used can be verified.

There might not be one. Thanks for adding tests!

> If we are returning DateType.get for Days why not for Month/Year as well

The values for those aren't stored as dates. For example, 1990 is stored as 20.

> Anything specific I need to test/validate if this change impacts the metadata tables?

Existing tests should cover it. The change should automatically update the Spark representation as well. Just fix any test failures, if there are any.

**Comment by manishmalhotrawork** [comment]
@rdblue , wondering if this issue is resolved by the #424 ?

**Comment by rdblue** [comment]
Yep. Thank you!

**Comment by waterlx** [comment]
Hi @rdblue , I am not sure if the table of "partition transforms" on the [doc](https://iceberg.apache.org/spec/#partition-transforms) needs to update to reflect this change. The row of "day" of the table. Would you please advice? Thanks!

**Comment by rdblue** [comment]
@waterlx, I think you're right. We should update that line. Do you want to open a PR?

**Comment by waterlx** [comment]
Hi @rdblue , would you please review PR #447 at your most convenience?
