### ISSUE TITLE
add build documents from source code

### ISSUE THREAD

**Issue by melin** [apache/incubator-iceberg#286]
add build documents from source code to help users quickly use

**Comment by rdblue** [comment]
Do you mean how to invoke the build? If so, you can run this to build and run tests:

```
./gradlew build
```

If you want to skip tests, run:

```
./gradlew build -x test
```

**Comment by rdblue** [comment]
Would you like to open a PR to add those to the README?

**Comment by timmylicheng** [comment]
Just started to get into iceberg. I figured to do a PR for this: https://github.com/apache/incubator-iceberg/pull/304

**Comment by timmylicheng** [comment]
#304 is merged in.
