### ISSUE TITLE
Replace Murmur3 x86_32 hash with XXH64

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/incubator-iceberg#288]
Since [XXH64 ](http://www.xxhash.com/) is faster and architecture independent, so we may want to consider to replace the current x86 version Murmur3Hash with the XXH64.

**Comment by rdblue** [comment]
We can possibly add XXH64 later, but the Iceberg spec requires Murmur3. We would need to deprecate Murmur3 and I'm not convinced that it is worth the change just yet.

**Comment by rdblue** [comment]
I'm closing this, but we can reopen it if we decide to add XXH64 support in the future.
