### ISSUE TITLE
Update scala style MultipleStringLiteralsChecker or remove it

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/incubator-iceberg#289]
With the current checker setting of ignoreRegex `^""$` (which is the default), it cannot use the string interpolation variables more than three times. Please see a related issue [here](https://github.com/scalastyle/scalastyle/issues/100). I can resolve this by setting ignoreRegex to `^""?$` as listed in the above link. 

Besides, I found it is not convenient to use the checker, for example, when concatenating a path it may need to use `/` several times, I don't want to define a variable. Since I don't see the checker enabled in spark project, can we also remove it?

**Comment by rdblue** [comment]
What does the rule catch when it isn't misbehaving?

**Comment by chenjunjiedada** [comment]
The rule limits the reference of same literal string up to specific times, which is set to 2 now. String literals like ",", "/", "=" and etc are commonly used and easily hit the rule.

**Comment by rdblue** [comment]
Is this across files, or just within a single file?

**Comment by chenjunjiedada** [comment]
From the tip from IntelliJ, it is from a single file.  What 's your preference? Remove it or fix it?

**Comment by rdblue** [comment]
If this is in a single file, then let's remove it. I think the real value is across multiple files so we don't repeat constants.
