### ISSUE TITLE
Add parameter checks for HadoopTables#create

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/incubator-iceberg#290]
The `HadoopTables#create` doesn't check whether the spec is null which may lead to NullPointerExeception.  For example, a user may use `specForTables` to get partition spec for a table and then pass it to `HadoopTables#create`, it throws NullPointerExeception if the table doesn't have partition column.

IIUC we should support creating the table which has no partition. So what is the default behavior? Shall we use a PartitionSpec with an empty PartitionField list? 
`PartitionSpec.buildfor(shema).build()`

**Comment by rdblue** [comment]
Unpartitioned tables use `PartitionSpec.unpartitioned()`.

**Comment by chenjunjiedada** [comment]
So it should return PartitionSpec.unpartitioned() for specForTables when it found no partition column.

**Comment by rdblue** [comment]
Thanks for fixing #292! Do you plan to add more checks for this issue was well?

**Comment by chenjunjiedada** [comment]
Yes, I will spend some time on this.

**Comment by chenjunjiedada** [comment]
close via https://github.com/apache/incubator-iceberg/pull/298
