### ISSUE TITLE
Respect commit.manifest.target-size-bytes in MergeAppend and FastAppend

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#307]
`MergeAppend` and `FastAppend` are writing all added files to a new manifest. `MergeAppend` also has logic to merge small manifests into bigger ones. However, there is no logic to prevent writing large manifests if the number of new files is big.

We can respect `commit.manifest.target-size-bytes` in `MergeAppend` and `FastAppend` and split new files into multiple manifests.

**Comment by aokolnychyi** [comment]
@rdblue @danielcweeks what do you think? I am not sure we need this logic in `FastAppend` but it seems reasonable in `MergeAppend`. Alternatively, this can be done by a separate process that will leverage `RewriteManifests`.

**Comment by rdblue** [comment]
This sounds good to me, but I'm concerned about the number of files that would be required in a single commit to read the target manifest size. How many files are you committing at once? Are those files reasonably sized?

**Comment by aokolnychyi** [comment]
I saw one table with a wrong partitioning that caused a commit of ± 2 million files and ±500 MB manifest size. Of course, that was a configuration error.

Manifest size can be around 8MB if you commit ±10000 files. Let's actually keep this open and not address it now. Even if we write a couple of TB in one batch, it shouldn't be a big problem to have a slightly bigger manifest. Might not be worth the complexity.

**Comment by rdblue** [comment]
I agree. There may be use cases that require this, but we don't usually expect this to happen without a configuration problem like your case.

**Comment by rdblue** [comment]
I'm going to close this. We can reopen it if we hit cases where manifests are too large and the reason for the number of files is reasonable.
