### ISSUE TITLE
Add startsWith predicate

### ISSUE THREAD

**Issue by rdblue** [apache/incubator-iceberg#31]
Some users have requested prefix matching or startsWith.

This issue was migrated from https://github.com/Netflix/iceberg/issues/49.

**Comment by rdblue** [comment]
The Netflix repository had an incomplete PR that is a good starting point: https://github.com/Netflix/iceberg/pull/78

**Comment by xabriel** [comment]
#327 was merged. Should we close this?

**Comment by rdblue** [comment]
Feel free to close issues like this. It's easy to reopen them if we need to.

**Comment by xabriel** [comment]
I only have comment privileges :)

**Comment by rdblue** [comment]
I didn't realize that was locked down. Good to know, thanks!
