### ISSUE TITLE
Concurrent appends to the same table using HiveCatalog lead to deadlock in the Metastore

### ISSUE THREAD

**Issue by rdsr** [apache/incubator-iceberg#366]
I've noticed that, appending files to the same table from multiple threads takes a very large amount of time. The problem is more evident if the number of threads are more. From the logs it seems there's deadlock in the Metastore.

Below is the log I'm pasting from the test case.

> [main] INFO org.apache.iceberg.BaseMetastoreTableOperations - Refreshing table metadata from new version: file:/var/folders/dg/xnsw71ls347dkft4qr284zr4000bt7/T/hive3179686150067127808/hivedb.db/tbl/metadata/00000-5001916d-81a9-408c-ad9e-9cdec89090e1.metadata.json
> [main] INFO org.apache.iceberg.BaseMetastoreTableOperations - Refreshing table metadata from new version: file:/var/folders/dg/xnsw71ls347dkft4qr284zr4000bt7/T/hive3179686150067127808/hivedb.db/tbl/metadata/00000-5001916d-81a9-408c-ad9e-9cdec89090e1.metadata.json
> Starting append 0
> Starting append 1
> Starting append 2
> Starting append 3
> Starting append 4
> Starting append 5
> Starting append 6
> Starting append 7
> Starting append 8
> Starting append 9
> 2019-08-08 11:08:59,302 WARN  [pool-3-thread-2] txn.TxnHandler (TxnHandler.java:checkRetryable(982)) - Deadlock detected in checkLock(CheckLockRequest(lockid:7) ). Will wait 200ms try again up to 10 times.
> 2019-08-08 11:09:19,518 WARN  [pool-3-thread-3] txn.TxnHandler (TxnHandler.java:checkRetryable(982)) - Deadlock detected in checkLock(CheckLockRequest(lockid:6) ). Will wait 200ms try again up to 10 times.
> 2019-08-08 11:09:39,743 WARN  [pool-3-thread-3] txn.TxnHandler (TxnHandler.java:checkRetryable(982)) - Deadlock detected in checkLock(CheckLockRequest(lockid:6) ). Will wait 400ms try again up to 9 times.
> [pool-6-thread-7] INFO org.apache.iceberg.SnapshotProducer - Committed snapshot 3707713582032677660 (MergeAppend)

The testcase is published here: https://github.com/apache/incubator-iceberg/compare/master...rdsr:hivecatalog_deadlock?expand=1

Most likely not a bug in Iceberg, but creating ticket for tracking purposes

**Comment by rdblue** [comment]
I'm not sure this is a deadlock. It might be that the concurrent appends keep failing and retrying and one is always holding the lock attempting to commit.

**Comment by aokolnychyi** [comment]
HMS has an internal mechanism for recovering in such cases, which might be slow in highly concurrent environments. One point that concerns me a bit is that we constantly send check lock requests without any time between requests, which puts quite some pressure on HMS (see `HiveTablesOperations$acquireLock`).

The following succeeds in 2-20 seconds after adding a sleep between check lock requests (the test is identical to what @rdsr had, except table properties):

```
    Table icebergTable = catalog.loadTable(TABLE_IDENTIFIER);

    icebergTable.updateProperties()
        .set(TableProperties.COMMIT_NUM_RETRIES, "10")
        .set(TableProperties.COMMIT_MIN_RETRY_WAIT_MS, "50")
        .set(TableProperties.COMMIT_MAX_RETRY_WAIT_MS, "10")
        .commit();

    String fileName = UUID.randomUUID().toString();
    DataFile file = DataFiles.builder(icebergTable.spec())
        .withPath(FileFormat.PARQUET.addExtension(fileName))
        .withRecordCount(2)
        .withFileSizeInBytes(0)
        .build();

    // If we reduce the number of threads, the problem is less evident.
    ExecutorService executorService = MoreExecutors.getExitingExecutorService(
        (ThreadPoolExecutor) Executors.newFixedThreadPool(10));

    Consumer<Integer> t = (idx) -> {
      long startTime = System.currentTimeMillis();
      System.out.println("Starting append " + idx);
      icebergTable.newAppend().appendFile(file).commit();
      System.out.println("Time taken for append " + idx + "in thread " + Thread.currentThread() + " = "
          + (System.currentTimeMillis() - startTime + "ms"));
    };

    for (int i = 0; i < 10; i++) {
      int finalI = i;
      executorService.submit(() -> t.accept(finalI));
    }

    executorService.shutdown();
    executorService.awaitTermination(1, TimeUnit.MINUTES);
```

**Comment by aokolnychyi** [comment]
Below is the part in `HiveTableOperations` I was talking about:
```
    while (state.equals(LockState.WAITING)) {
      lockResponse = metaClients.run(client -> client.checkLock(lockId));
      state = lockResponse.getState();
    }
```

**Comment by aokolnychyi** [comment]
@rdblue @rdsr what do you guys think about adding a timeout between check lock requests?

**Comment by rdblue** [comment]
Yeah, definitely. Good catch.

**Comment by rdblue** [comment]
Sounds like a blocker to me.

**Comment by aokolnychyi** [comment]
I'll follow up with a PR then
