### ISSUE TITLE
Iceberg failed to work with embedded metastore, which is by default in Spark

### ISSUE THREAD

**Issue by jerryshao** [apache/incubator-iceberg#370]
Current iceberg cannot work against Spark local mode with embedded metastore, it will throw an exceptions shows as below. The issue seems like missing HIVE_LOCKS table in derby. We should figure out a way to either inject HIVE_LOCKS when starting Spark, or disable lock when using embedded metastore.

>Caused by: org.apache.hadoop.hive.metastore.api.MetaException: Unable to update transaction database java.sql.SQLSyntaxErrorException: Table/View 'HIVE_LOCKS' does not exist.
at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)

**Comment by jerryshao** [comment]
Working on it, will submit a PR.

**Comment by jerryshao** [comment]
After spending a bit time on this issue, seems this problem is more complicated than I thought, it is not just "HIVE_LOCKS" table doesn't exist. A more severe problem is that embedded metastore only allows one Hive client, if Spark HiveExternalCatalog created hive client, then Iceberg cannot create another, vice versa.

A simple fix would be to reject using Iceberg datasource when Spark is configured with embedded metastore. A more complicated fix would be to share the same hive client with Spark, which requires some reflections to get hive client object from Spark.

@rdblue what's your opinion on it? I would suggest to use a simple solution.

**Comment by rdblue** [comment]
I think the simple solution makes sense -- if we can provide an error message that states what's happening that would be really helpful.

**Comment by rdblue** [comment]
Maybe we should also give an example of starting up a docker container with a hive metastore service?

**Comment by jerryshao** [comment]
> Maybe we should also give an example of starting up a docker container with a hive metastore service?

Yes, that seems useful.

**Comment by lohao** [comment]
> After spending a bit time on this issue, seems this problem is more complicated than I thought, it is not just "HIVE_LOCKS" table doesn't exist. A more severe problem is that embedded metastore only allows one Hive client, if Spark HiveExternalCatalog created hive client, then Iceberg cannot create another, vice versa.
> 
> 
> 
> A simple fix would be to reject using Iceberg datasource when Spark is configured with embedded metastore. A more complicated fix would be to share the same hive client with Spark, which requires some reflections to get hive client object from Spark.
> 
> 
> 
> @rdblue what's your opinion on it? I would suggest to use a simple solution.

How to reject using Iceberg data source?

**Comment by pPanda-beta** [comment]
I would recommend to use schematool or any other in-memory db than derby. 

More at: 
https://issues.apache.org/jira/browse/HIVE-21302

**Comment by vinitamaloo-asu** [comment]
@jerryshao could you shed more light on the more complex approach to share the hiveClient?
