### ISSUE TITLE
Add in and notIn predicates

### ISSUE THREAD

**Issue by rdblue** [apache/incubator-iceberg#39]
Currently, set inclusion is implemented using a tree of `equals` predicates joined with `or` predicates. It would be much more efficient to add support for `in` and `notIn` predicates.

**Comment by shawnding** [comment]
Taking a stab at this , If no one follows, I will do this.

**Comment by rdblue** [comment]
Merged #594. Thanks @jun-he!

**Comment by aokolnychyi** [comment]
@rdblue @jun-he can we close this one?
