### ISSUE TITLE
Re-deploy web page to fix #333

### ISSUE THREAD

**Issue by waterlx** [apache/incubator-iceberg#394]
On the page of https://iceberg.incubator.apache.org/spark/,  in "Spark 2.4 is limited to reading and writing existing Iceberg tables. Use the Iceberg API to create Iceberg tables", URL of "Iceberg API" is pointing to "https://iceberg.incubator.apache.org/spark/api", which does not exist

**Comment by waterlx** [comment]
@rdblue I am not sure if the website is not deployed after [issue 333](https://github.com/apache/incubator-iceberg/pull/333) is merged. Would you please have a check at your convenience?

**Comment by waterlx** [comment]
Hi @rdblue could you please have a check if the web page needs to be re-deployed to fix #333?

**Comment by rdblue** [comment]
I just redeployed. Looks like it works to me.

**Comment by waterlx** [comment]
The web page is updated, thanks!
