### ISSUE TITLE
Add timeout for acquiring locks in HiveTableOperations

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#399]
We need to add a timeout in `HiveTableOperations$acquireLock`.

**Comment by waterlx** [comment]
Working on this. Will submit a PR.

**Comment by waterlx** [comment]
@aokolnychyi Would you please help to close this issue as PR #736 is merged?

**Comment by aokolnychyi** [comment]
Thanks for fixing it, @waterlx!
