### ISSUE TITLE
Build failure with NPE in non standard git checkout

### ISSUE THREAD

**Issue by kings129** [apache/incubator-iceberg#400]
Build script use gitVersion(), it will throw NullPointerException when no .git directory exists.
This is an issue when I try to build iceberg in our CI system which uses git worktree checkout.

My fix was adding a wrapper on gitVersion() to catch NPE and use a default version. Does this worth contributing back?

**Comment by rdblue** [comment]
I think we will need to fix this so that our source releases can be built without a .git directory. Thanks for reporting this!

**Comment by rdblue** [comment]
Merged the fix. Thanks @kings129!
