### ISSUE TITLE
Provide a way to show metadata for a Hadoop table

### ISSUE THREAD

**Issue by waterlx** [apache/incubator-iceberg#404]
https://iceberg.incubator.apache.org/spark/#inspecting-tables shows the way to inspect metadata for an iceberg table in HiveMetaStore. But when it comes to an iceberg table which is identified by a HDFS patch, I did not see a way (or guide) to access its metadata, like history, snapshot, manifest or files.

**Comment by waterlx** [comment]
@xabriel yes, I would like to work on this but not start it yet. 
But I am not sure if this issue makes sense and its priority. Would you please share your insights about those?

**Comment by xabriel** [comment]
This issue makes sense to me @waterlx . We should be able to study the metadata from an Iceberg table without having a dependency on Hive. I think its important for feature parity.

We should agree on the interface. For Hive tables, @rdblue chose to extend the namespace:
```
spark.read
  .format("iceberg")
  .load("db.table.history")
```

where `db.table` is the Hive object, and `.history` is the namespace extension to access the "history" metadata.

Problem is, with an URI such as we have in HDFS or Object Storage, that would look weird:
```
spark.read
  .format("iceberg")
  .load("load("adl://bucket/path/to/table.history")
```

So maybe we should make this an option?
```
spark.read
  .format("iceberg")
  .option("read-metadata", "history")
  .load("load("adl://bucket//path/to/table")
```

CC @rdblue

**Comment by rdblue** [comment]
I think @xabriel did a good job summarizing the problem. We can support this for path-based tables, but we need to come up with a way to identify that we want to read a metadata table in the URI. What about adding anchors, like `adl://bucket/path/to/table#history`?

**Comment by xabriel** [comment]
Anchors sound good to me.

**Comment by waterlx** [comment]
Cool @xabriel ! I am trying to draft the patch

**Comment by waterlx** [comment]
Hi @xabriel sorry that I do not have enough bandwidth to work this out within a week or two. Please feel free to pick this up if you have time.
