### ISSUE TITLE
Optimize StreamingDelete

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#409]
We should use optimized deletes in `StreamingDelete` from #387.

**Comment by rdblue** [comment]
What do you mean? The changes in #387 already apply to `StreamingDelete` because it extends `MergingSnapshotProducer`.

**Comment by aokolnychyi** [comment]
As I understand, `StreamingDelete` uses `delete(CharSequence)` instead of `delete(DataFile)`. So, `deleteFilePartitions` is not set.

**Comment by rdblue** [comment]
Okay, I see. Yeah, we should expose the DataFile method as well.
