### ISSUE TITLE
Consider building a HadoopCatalog

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#422]
I think we should consider building a `Catalog` implementation that relies on renames for committing metadata. That way, users will be able to avoid using HMS if they don't have one yet.

One of the challenges is `renameTable` as Iceberg uses absolute paths in the metadata.

**Comment by chenjunjiedada** [comment]
This is interesting, I'd like to spend some effort on this if you haven't started it yet.

Regarding the `renameTable` challenge, The `renameTable`  requires to rename the location of the table, for example, `hdfs://tableA -> hdfs://tableB`, which means to rename the directory and update the JSON file in both file version and location value of its content as well.  The challenge is to do them atomically via hdfs rename. Could you please help to correct me if my understanding is not correct?

**Comment by aokolnychyi** [comment]
@chenjunjiedada it would be great if you could work on this!

One of the ideas was to use smth like this: `hdfs://nn:8020/iceberg/warehouse/(DB).db/(TABLE)`.

I think the challenge with `renameTable` is that Iceberg keeps absolute paths in the metadata. So, we might need to keep data files somewhere else (controlled by `write.folder-storage.path`). Also, we need to avoid rewriting manifests while renaming a table. I think if we keep only `*.metadata.json` files under those locations, it should work (maybe `write.metadata.path` can help). Alternatively, we can consider using relative paths in the metadata. I haven't thought a lot about what's best.

@rdblue what are you thoughts on this?

**Comment by rdblue** [comment]
I think adding a HadoopCatalog sounds good, but we should plan on continuing to support tables identified by full paths.

For rename, I would probably just throw an exception and disallow rename.

**Comment by aokolnychyi** [comment]
I just had the chance to go through our implementation done in #529. Seems reasonable. Thanks, @chenjunjiedada! I am closing this issue.

**Comment by rdblue** [comment]
Thanks for updating the issue!
