### ISSUE TITLE
Optimize ParquetMetricsRowGroupFilter by using ByteBuffer

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#423]
See [this link](https://github.com/apache/incubator-iceberg/pull/398#discussion_r318196009) for details.

**Comment by sujithjay** [comment]
Hi @aokolnychyi , are you already working on this story? If not, I would like to give this a try.

**Comment by aokolnychyi** [comment]
Hi, @sujithjay. Sure, go ahead!
