### ISSUE TITLE
Handle dates in Conversions$fromPartitionString

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#428]
See [here](https://github.com/apache/incubator-iceberg/pull/374/files#r318675192) for details.

**Comment by chenjunjiedada** [comment]
@aokolnychyi Do you have the plan to implement this? Or any further consideration?

BTW, do we want to support TimeStamp type as well?

**Comment by chenjunjiedada** [comment]
@aokolnychyi, would you please take a look on this?

**Comment by aokolnychyi** [comment]
@chenjunjiedada Sorry for the delay. I was out for a week. I haven't started working on this. Would you be interested to pick this up?

**Comment by aokolnychyi** [comment]
As discussed in #483, this has very limited applicability (i.e. only for importing existing Spark tables).

**Comment by rdblue** [comment]
Fixed by #506.
