### ISSUE TITLE
Add guide about how to set hive.metastore.warehouse.dir

### ISSUE THREAD

**Issue by waterlx** [apache/incubator-iceberg#436]
The page of [API quick start](http://iceberg.apache.org/api-quickstart/) shows the example to use Spark's Hadoop configuration to get a Hive catalog. If `hive.metastore.warehouse.dir` is not set properly, the example code will fail with exception. See `HiveCatalog#defaultWarehouseLocation()`. 
We might need to add more guide about how to set `hive.metastore.warehouse.dir`, which makes it more friendly to the rookies (not familiar with Spark, Hadoop or Hive)

**Comment by waterlx** [comment]
PR #437 is closed by mistake. Re-open a new PR as #440 to address Ryan's comment in PR #436.

**Comment by rdblue** [comment]
Closing this as well. Feel free to reopen if it turns out to be an issue.
