### ISSUE TITLE
Encryption not working

### ISSUE THREAD

**Issue by bsannicolas** [apache/incubator-iceberg#451]
I don't know if I'm doing something wrong but I haven't been able to get encryption to work with Iceberg. I've created an implementation of the EncryptionManager that uses AES encryption with static keys and stores some dummy data in the EncryptionKeyMetadata. I specified my encryption manager in a subclass of TableOperations. 

In my test table, the encrypt/decrypt methods are being called (the output files are encrypted) and I can see my key metadata in the manifest files. However, when decrypt is called EncryptedInputFile.keyMetadata().buffer() is always null (it's EncryptionKeyMetadata.empty()). I can provide code examples if necessary but I'm wondering if there's a config I'm missing or if there's a working example I can use to work backwards?

**Comment by rdblue** [comment]
@bsannicolas, I think what's happening is that scan planning doesn't project the encryption metadata column. You can see the columns it uses here: https://github.com/apache/incubator-iceberg/blob/master/core/src/main/java/org/apache/iceberg/DataTableScan.java#L41-L44

I think if you add encryption metadata to that list, you'd be able to read the files.

**Comment by bsannicolas** [comment]
Yeah that seems to have fixed the problem. Thanks!

**Comment by rdblue** [comment]
@bsannicolas, do you want to open a PR to fix this in master?

**Comment by bsannicolas** [comment]
@rdblue https://github.com/apache/incubator-iceberg/pull/469

**Comment by rdblue** [comment]
Fixed by #469. Thanks, @bsannicolas!
