### ISSUE TITLE
DataFrame generated by Seq() might have schema conflict with Iceberg

### ISSUE THREAD

**Issue by waterlx** [apache/incubator-iceberg#457]
Suppose that we have a DataFrame like:
``` scala
scala> val df = Seq("INFO").toDF("level")
df: org.apache.spark.sql.DataFrame = [level: string]

scala> df.printSchema
root
 |-- level: string (nullable = true)
```
and when I trying to write it into Iceberg table with the following schema,
``` scala
val schema = new Schema(
      NestedField.required(1, "level", StringType.get())
)
```
it is rejected by the following error message:
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot write incompatible dataset to table with schema:
table {
  1: level: required string
  2: event_time: optional timestamptz
  3: id: required int
}
Problems:
* level should be required, but is optional
```

**Comment by waterlx** [comment]
String in Spark has default nullable setting as "true", and Iceberg has the following code to decide required or optional with respect to nullable()
``` java
// public Type struct(StructType struct, List<Type> types) in SparkTypeToType.java
if (field.nullable()) {
        newFields.add(Types.NestedField.optional(id, field.name(), type, doc));
} else {
        newFields.add(Types.NestedField.required(id, field.name(), type, doc));
}
```
When in Iceberg, we add a " required" field as StringType, the error message is reported.
This issue could be resolved by explicitly specifying "nullable" for schema in Spark, like:
``` scala

val schema = StructType(List(
    StructField("integer_column", IntegerType, nullable = false),
    StructField("string_column", StringType, nullable = true),
    StructField("date_column", DateType, nullable = true)
```

**Comment by sujithjay** [comment]
You should define your iceberg schema as:
```
val schema = new Schema(
      NestedField.optional(1, "level", StringType.get())
)
```

**Comment by waterlx** [comment]
@sujithjay , thanks for taking care of this!
I see your point by changing the Iceberg schema, but what if I do not want to make that field as "optional", and keep it as "required"?

**Comment by chenjunjiedada** [comment]
Found more discussion in #510

**Comment by aokolnychyi** [comment]
I am going to close this one as I think #514 fixed it. Feel free to reopen if needed, @waterlx.
