### ISSUE TITLE
Consider replacing TableOperations parameter in TableMetadataParser::read

### ISSUE THREAD

**Issue by lxynov** [apache/incubator-iceberg#459]
When using `TableMetadataParser::read` to get a `TableMetadata` instance, we have to pass a `TableOperations` instance as an argument. I think it might make sense to refactor and replace the `TableOperations` parameter with `FileIO`.

The rationale behind not using `TableOperations` is:
1. It saves the need to construct a `TableOperations` instance when all you want to is to get a table's metadata by parsing its metadata file. Consider a distributed system with a coordinator-worker architecture and it uses a metastore for cataloging. Let's say the coordinator is responsible for getting the metadata file's location and sending it to workers; and workers are responsible for getting the metadata. After the refactoring, the worker doesn't need to talk to the metastore anymore.
2. It's more intuitive because a `TableMetadata` instance reflects a table's state and is determined by only a set of metadata files. It's confusing to use a `TableOperations` instance to build it and have a `TableOperations` field inside the `TableMetadata` class.

The refactoring will involve classes including `TableMetadataParser`, `TableMetadata`, `SnapshotParser`, `BaseSnapshot`, `ManifestGroup`, etc. It looks feasible to replace/remove `TableOperations` from them.

Please LMK if anyone has comments. I can go ahead and try to refactor if this proposal is reasonable.

**Comment by aokolnychyi** [comment]
I like the idea but I am curious to know how we plan to replace `ops$current` and other calls.

**Comment by linxingyuan1102** [comment]
> I like the idea but I am curious how we plan to replace `ops$current` and other calls.

@aokolnychyi Thanks for the comment. As per my inspection, `ops$current` is called when `Snapshot::addedFiles`/`Snapshot::deletedFiles` is called. Essentially, it is used to get a `specLookup` function, which is essentially a mapping from spec ID to partition spec. I think it should be okay to store such a mapping in `BaseSnapshot`, i.e., to replace the `TableOperations` field with `Map<Integer, PartitionSpec>` and `FileIO`. Also, from my understanding, it's more intuitive to not let a certain `TableMetadata`'s behavior depend on the table's (future) state (`ops$current`). What do you think?

**Comment by aokolnychyi** [comment]
I wondered myself whether we can decouple `TableMetadataParser` from `TableOperations` at some point. It looked a substantial change to me and I didn't have time to investigate more. In my case, I had to provide `TableOperations` to read metadata from a file in order to register an existing table back. Personally, I would support this effort.

**Comment by linxingyuan1102** [comment]
I think the work can follow these steps:
1. Change the method signature of `ManifestReader::read` to let it accept a map from spec ID to partition spec.
2. Decouple `ManifestGroup` and `BaseSnapshot` from `TableOperations`. We'll need to include a `specsById` (a map from spec ID to partition spec) as their fields.
3. Decouple `TableMetadataParser` and `TableMetadata` from `TableOperations`.

So I've created PR #467 which does the first step. Please LMK if it makes sense.

**Comment by lxynov** [comment]
@aokolnychyi @rdblue Thanks for the review on #467 . I've created another PR #591 which finishes the decoupling work.
