### ISSUE TITLE
Conversions#fromPartitionString() does not support DateType

### ISSUE THREAD

**Issue by waterlx** [apache/incubator-iceberg#479]
1. DateType is not supported
Suppose that I have a partition spec using day transform, like:
```scala
val partitionSpec = PartitionSpec.builderFor(schema).day("event_time").identity("level").build() 
 // "event_time" is a TimestampType
```
Then I use DeleteFiles.builder to build a DeleteFile, like
```scala
val fileToDelete1 = DataFiles.builder(partitionSpec)
      .withPartitionPath("event_time_day=2020-01-01/level=ERROR")
      ...
```
The request is rejected by `Unsupported type for fromPartitionString: date`, because TypeID.DATE is not any "case" in the clause of "switch...case"
#279 changes day transform to return DateType instead of IntegerType

**Comment by aokolnychyi** [comment]
@waterlx is it the same as [this issue](https://github.com/apache/incubator-iceberg/issues/428)?

**Comment by waterlx** [comment]
> @waterlx is it the same as [this issue](https://github.com/apache/incubator-iceberg/issues/428)?
@aokolnychyi , yes, they are the same. Thanks for checking that. I will close this issue as a duplication of #428
