### ISSUE TITLE
NPE in FindFiles when there is no snapshot

### ISSUE THREAD

**Issue by waterlx** [apache/incubator-iceberg#501]
Though it seems not a valid use case(where I'm trying to get data files when there is no snapshot, that is, the Iceberg table just get created), NPE is not quite friendly...
https://github.com/apache/incubator-iceberg/blob/bd9f8c0b544a82293262e5eb924b9e081b28a1ba/core/src/main/java/org/apache/iceberg/FindFiles.java#L194
`snapshot` could be null when the table just gets created. `currentSnapshotId` in `TableMetadata` is  -1  and the map of `snapshotById` is with size of 0, the get() of map returns null as snapshot.

**Comment by rdblue** [comment]
I agree, this shouldn't throw a `NullPointerException`. Would you like to open a PR to fix this when there is no current snapshot?

**Comment by waterlx** [comment]
Sure, will submit a PR to fix that.
