### ISSUE TITLE
API for path generation in Iceberg frameworks

### ISSUE THREAD

**Issue by mccheah** [apache/incubator-iceberg#55]
In the integrations that Iceberg supports out of the box (Spark, Pig), the frameworks decide how to generate paths for written files. However, some sources would prefer to pick their own paths for new files. Some questions for designing such an API include:

- Should this be bundled with the `FileIO` API?
- Should such a path generation API be concerned about the file's partition values? Partition metadata would be required for the default implementation to maintain existing behavior for Spark.

**Comment by mccheah** [comment]
@vinooganesh @yifeih @rdblue

**Comment by rdblue** [comment]
I think this API should pass in the partition tuple. Now that I think about it, the metadata location is determined by the `TableOperations` implementation, not by `FileIO`. I think it would make sense to keep those in the same place. So `TableOperations` would be responsible for determining where to place both metadata and data files, while `FileIO` would just handle low-level file tasks.

**Comment by mccheah** [comment]
Ok I'll start taking a look at this now!

**Comment by rdblue** [comment]
@mccheah, in that case is this something that we should add to the `FileIO` interface? It wouldn't be that much of a stretch to do path selection as well. What do you think?

**Comment by mccheah** [comment]
Yup I don't have a strong opinion here, so let's bundle it with the FileIO interface. I'll propose a diff but I anticipate wanting to fine tune the exact method signatures as part of the PR review.

**Comment by mccheah** [comment]
Looks like this is done! I'll close it.

**Comment by xabriel** [comment]
(For completeness, linking this issue to PR that made it to master: https://github.com/apache/incubator-iceberg/pull/87)
