### ISSUE TITLE
Iceberg tables should allow for automatic table creation when writing if table not exists already

### ISSUE THREAD

**Issue by goldentriangle** [apache/incubator-iceberg#555]
I think this is a special case for https://github.com/apache/incubator-iceberg/issues/540.

When writing a spark dataframe into iceberg table, if the table doesn't exist, iceberg should create the table/schema automatically/implicitly

**Comment by rdblue** [comment]
We are planning on adding support for the new logical plans in Spark 3.0. That will include support fro common SQL statements, like `CREATE TABLE ... AS SELECT ...` as well as `REPLACE TABLE ... AS SELECT ...`. It will also include support for the new [DataFrameWriterV2](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/DataFrameWriterV2.scala) API that can be used for the same operations. The new API looks like this:

```scala
df.writeTo("db.table").append()
df.writeTo("db.table").partitionBy(hours($"ts")).create()
df.writeTo("db.table").partitionBy(hours($"ts")).createOrReplace()
```
