### ISSUE TITLE
Support recognizing the column represented with an array of fields

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/incubator-iceberg#598]
Some engines may express columns with an array of fields, such as `TableChange` API in Spark 3.0. We may need to consider supporting adding an API in `Schema`, e.g. `findField(String[] fields)`.

@rdblue, Does that make sense?

**Comment by rdblue** [comment]
Right now, we use a column key to do this to avoid traversing the schema. The field name array should be converted to dot notation: `["a", "b.c"]` gets converted to `"a.b.c"` and that key is looked up in the field index.

I don't think we need to add an array version. There isn't much value and that makes the API more confusing. For example, users may think it is better to use the array version and attempt to parse identifiers, when there is no need to do it. The point of this simplification is to avoid needing to parse identifiers.

**Comment by chenjunjiedada** [comment]
The concern is if we convert array to dot notation, different column keys may have the same result. For example: `["a", "b.c"], ["a", "b", "c"]` as well as other variants. How can we distinguish them?

**Comment by rdblue** [comment]
Iceberg doesn't allow conflicting names that have the same dot notation. You can have `["a", "b.c"]` or `["a", "b", "c"]`, but not both. I think this is a reasonable restriction because people never create schemas that are so hard for humans to understand because "a.b.c" could mean two different fields.

**Comment by chenjunjiedada** [comment]
It makes sense if Iceberg has the restriction. I checked that when adding a column, the restriction works. While I can still define a SCHEMA like below and use it to create a table:
```java 
  Schema SIMPLE_SCHEMA = new Schema(
      required(1, "id", Types.IntegerType.get()),
      optional(2, "data", Types.StringType.get()),
      required(3, "a", Types.StructType.of(
          required(4, "b", Types.StructType.of(
              required(5, "c", Types.BooleanType.get())
          )),
          required(6, "b.c", Types.BooleanType.get())
      ), "struct of named boolean options")
  );
```
Do we need a validator for schema? Though I think no one would intend to define schema like this. Or I may miss some checks.

**Comment by rdblue** [comment]
It's always a good idea to improve error messages. If you can create a schema like this and don't get an error or get a strange error message, we should fix it and throw an exception while creating the instance.
