### ISSUE TITLE
Consider to support namespace in HiveCatalog

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/incubator-iceberg#626]
Currently, HiveCatalog uses the first level of the namespace. Do we want to support multiple namespace levels in HiveCatalog? If not, we may need to update the document in the condition check.

**Comment by rdblue** [comment]
No, the `HiveCatalog` in Iceberg should follow the conventions of Hive, and Hive only supports one namespace level, called "database".

**Comment by chenjunjiedada** [comment]
I see. Thanks
