### ISSUE TITLE
Add cherry-pick operation

### ISSUE THREAD

**Issue by rdblue** [apache/incubator-iceberg#629]
Iceberg supports the WAP pattern, where a new commit can be staged instead of replacing the current table snapshot. But the only way to apply these changes currently is to use a rollback operation to set the current snapshot to the staged one.

This would be much more flexible and support concurrent writers if Iceberg supported a way to pick changes from one snapshot and apply them to another, like git's cherry-pick operation.

A cherry-pick operation is fairly simple for appends and rewrites because the individual file changes would be applied directly. Overwrites are more difficult because the overwritten data may have changed. An early version can support just append and rewrite.

**Comment by aokolnychyi** [comment]
Does this duplicate #42? Shall we close that one?

**Comment by rominparekh** [comment]
@prodeezy and I are working on an initial implementation to get community feedback. Thanks.

**Comment by prodeezy** [comment]
Added an initial PR for review .. https://github.com/apache/incubator-iceberg/pull/695

**Comment by prodeezy** [comment]
We can close this now @rdblue?

**Comment by rdblue** [comment]
Yes, and I closed #42 as Anton pointed out.
