### ISSUE TITLE
Remove gradle/wrapper/gradle-wrapper.jar from repo

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#638]
It seems we accidentally added  `gradle/wrapper/gradle-wrapper.jar` in PR #610.

**Comment by aokolnychyi** [comment]
@Fokko did we deliberately add `gradle/wrapper/gradle-wrapper.jar`?

**Comment by aokolnychyi** [comment]
It seems it should be downloaded according to [this](https://github.com/apache/incubator-iceberg/commit/789eba39012b7a18076e09662af7624101b0e060#diff-eb34851cc3b98933dbb0a257c9b7b097) commit.

**Comment by Fokko** [comment]
Oops! My mistake. This jar should not be part of the repo. I've created a PR: https://github.com/apache/incubator-iceberg/pull/639
