### ISSUE TITLE
Use a pool of metastore clients in HiveTableOperations

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#64]
I think it would be great to support a pool of metastore clients in `HiveTableOperations`.

There are a few reasons for that:

**Resource Utilization**

Currently, we create a new metastore client each time we load a table. This happens because we create a new instance of `HiveTableOperations`. If we keep producing new clients, our metastore might stop replying. For example, existing Hive tests will break if you share the same metastore among all 3 tests.

**Thread-Safety**

Currently, `HiveTableOperations` are not thread-safe. We could solve that via a thread-local client, but the first point will remain.

**Comment by rdblue** [comment]
This was fixed in #166.
