### ISSUE TITLE
Refactor metadata table tests in Spark to share the logic

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#659]
Right now, `TestIcebergSourceHadoopTables` and `TestIcebergSourceHiveTables` share the logic for metadata table tests. I think it would be a good idea to refactor it into a common parent class.

**Comment by meetchandan** [comment]
Should this be closed?

**Comment by aokolnychyi** [comment]
I could miss something but I still see duplicate logic in those classes for metadata table tests.

**Comment by golammott** [comment]
Hi @aokolnychyi, first time contributor attempting to help with this one. Ive submitted PR above let me know if this wasn't exactly what you had in mind and I can make the necessary changes.

**Comment by aokolnychyi** [comment]
@golammott, sorry I was out for a while. Thanks for contributing this!
