### ISSUE TITLE
Add Parquet user-defined predicate to push down StartsWith

### ISSUE THREAD

**Issue by rdblue** [apache/incubator-iceberg#682]
Parquet cannot currently push down startsWith predicates because it doesn't have a built-in implementation. Iceberg should add a user-defined predicate to push it down.

**Comment by waterlx** [comment]
Hi @rdblue has this issue addressed by PR #327 ? Could you please close this issue?

**Comment by aokolnychyi** [comment]
I think #327 provided a basis and #398 implemented `startsWith` in our dictionary and metrics filters in Parquet. @rdblue, is this what you mean by this issue?

**Comment by maqroll** [comment]
Sorry to jump in but maybe this issue refers to handle STARTS_WITH case with an UserDefinedPredicate [here](https://github.com/apache/incubator-iceberg/blob/542c0b3d49518b5105d4f9a30c65f474ea62fd97/parquet/src/main/java/org/apache/iceberg/parquet/ParquetFilters.java#L177).

**Comment by rdblue** [comment]
When I opened this issue, I was thinking about the old read path. That's the one that @maqroll correctly pointed to. But we now use the new read path and the row group filters are [`ParquetMetricsRowGroupFilter`](https://github.com/apache/incubator-iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java) and [`ParquetDictionaryRowGroupFilter`](https://github.com/apache/incubator-iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/ParquetDictionaryRowGroupFilter.java). We need to add support to those classes for the `startsWith` predicate added by #327.

Part of the advantage of the new read path is that we don't need to use Parquet's filter API, which is difficult to work with and doesn't natively support all of the expression types that Iceberg uses.

**Comment by rdblue** [comment]
I'm going to close this one since I think it covers a case that we don't really need to worry about.

**Comment by bachar84** [comment]
In my humble opinion, issue #327 is the roots of persecution

**Comment by rdblue** [comment]
> In my humble opinion, issue #327 is the roots of persecution

I'm not sure I understand you. What do you mean?

**Comment by aokolnychyi** [comment]
I think `SparkFilters` already converts startsWith correctly. However, we need to update it to use new expressions for IN as it still rewrites it.

**Comment by rdblue** [comment]
I agree. I opened #748 to track updating `SparkFilters`.
