### ISSUE TITLE
Add Parquet user-defined predicates to push down IN and NOT_IN

### ISSUE THREAD

**Issue by rdblue** [apache/incubator-iceberg#683]
Parquet cannot currently push down IN and NOT_IN predicates because it has no built-in support. Iceberg should include a user-defined predicate that implements these so they can be pushed down.

**Comment by shawnding** [comment]
HI @rdblue : Is this means implements the IN and NOT_IN predicates into `ParquetMetricsRowGroupFilter` and `ParquetDictionaryRowGroupFilter`?

**Comment by rdblue** [comment]
@shawnding, Sorry, this was implemented in #600. I'll close this.

Thanks to @jun-he for fixing this one!

**Comment by shawnding** [comment]
OK

**Comment by waterlx** [comment]
@rdblue Would you please help to close this issue? It seems that I can not help to close the issues that are not opened by me 8-）
