### ISSUE TITLE
Support Decimal in Parquet predicates

### ISSUE THREAD

**Issue by rdblue** [apache/incubator-iceberg#684]
Parquet predicates currently do not support push-down on Decimal columns.

This will require detecting the decimal storage and building the correct predicate that uses an integer, long, or binary value.

**Comment by aokolnychyi** [comment]
@rdblue, we do support row group skipping for predicates on decimal columns, don't we?

**Comment by rdblue** [comment]
Iceberg doesn't currently support pushing down predicates because it can't translate from BigDecimal into predicates on Parquet primitives.

Parquet stats were also incorrect for decimals stored as Binary, but in that case the stats are suppressed so it is safe to push down the predicates. I think we just need to add the translation for int and long decimal storage, and a comparator for binary decimals.

**Comment by chenjunjiedada** [comment]
@rdblue, I 'm trying to understand this, please correct me if I'm wrong.

Currently, `ParquetFilters#getParquetPrimitive` doesn't handle the BigDecimal case, we should add branches to translate decimal literal to int, long (, and binary?) according to its precision. So that `ParquetFilter@predicate` can return a matched `pred` correctly. Also because DecimalLiteral uses a default comparator (null first + natural order) which cannot compare binary decimals so we need to create a new comparator such as `BinaryDeciamlComparator`

**Comment by chenjunjiedada** [comment]
@rdblue , Any comment on this? Thanks in advance!

**Comment by rdblue** [comment]
@chenjunjiedada, I think I was wrong about this issue. I was referring to the note here, where we are converting Iceberg filters to Parquet filters: https://github.com/apache/incubator-iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/ParquetFilters.java#L207

But that code path is only used when reading Parquet files with a Parquet `ReadSupport`. We don't do that for Spark, we use [the Iceberg reader](https://github.com/apache/incubator-iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java#L231-L233) now to avoid the overhead of `ReadSupport` and to implement our own row group filters (that support, for example, Decimal and IN).

The new read path already has support for decimal because it [converts Parquet min/max stats](https://github.com/apache/incubator-iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java#L104) to the objects that Iceberg uses. That [conversion supports decimal](https://github.com/apache/incubator-iceberg/blob/master/parquet/src/main/java/org/apache/iceberg/parquet/ParquetConversions.java#L71).

So the new read path that we actually use already supports decimal predicates. We could go back and fix the old read path, but I don't think that we want to spend the effort since the problem is knowing what physical type to pass to Parquet (int, long, or binary).

I think we should mark this issue completed. What do you think?

**Comment by aokolnychyi** [comment]
I also tested a simple query with row group skipping and it worked, that's why the confusion in [my earlier comment](https://github.com/apache/incubator-iceberg/issues/684#issuecomment-564014720).

**Comment by rdblue** [comment]
Sorry, that was my mistake.

**Comment by chenjunjiedada** [comment]
Thanks for your explanation.
