### ISSUE TITLE
Path in IcebergSource#findTable() could cause ambiguity

### ISSUE THREAD

**Issue by waterlx** [apache/incubator-iceberg#713]
When using IcebergSource#getTable(), path is the key to identify table in Iceberg in findTable(). Currently, the table is identified based on whether "path" contains "/", as:
```
if (path.contains("/")) {
  // hadoop table
} else {
  // hive table
}
```
When using source like ”parquet", I could specify "path" as "test", and it is treated as a relative path to working directory. But when trying to specify "path" as "test" against Iceberg, it might cause ambiguity. Current logic treats it as a hive table, but actually I would like to have a hadoop table (with a relative path)

**Comment by waterlx** [comment]
@rdblue Would you please share your opinions here at your mot convenience?

**Comment by rdblue** [comment]
Would using `./test` work to clarify?

I think that the current behavior is correct. Hive tables should be the default when there is a conflict because there are easy ways to modify the path to indicate a Hadoop table (like `./test`).

**Comment by waterlx** [comment]
Hi @rdblue, thanks for sharing your idea! 
How about making it more strict: when the path prefixes with "/", "./", "../", or [a hierarchical URI](https://docs.oracle.com/javase/8/docs/api/java/net/URI.html), it routes to Hadoop table, otherwise, it is routed to Hive table. Make sense to you? An initial PR is submitted as https://github.com/apache/incubator-iceberg/pull/719

**Comment by waterlx** [comment]
Close this issue due to the discussion in PR #719
