### ISSUE TITLE
Improve multi-threading in BaseRewriteManifests

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#726]
I think we should revisit multi-threading logic in `BaseRewriteManifests` as we are using a thread pool but all methods in `WriterWrapper` are synchronized.

**Comment by jun-he** [comment]
@aokolnychyi  Here, the thread pool used in `performRewrite` seems to be a shared one (https://github.com/apache/incubator-iceberg/blob/master/core/src/main/java/org/apache/iceberg/util/ThreadPools.java#L60).

If the same BaseRewriteManifests object's `apply` method was called twice at the same time, it is possible that the same WriterWrapper object was accessed by two different threads in this shared thread pool.

If this won't happen, I think we can drop `synchronized` in WriterWrapper.
