### ISSUE TITLE
[Incremental Scan] Expose an API in Spark to read incremental data

### ISSUE THREAD

**Issue by rdsr** [apache/incubator-iceberg#731]
Once #315 gets pushed we should expose a Spark API for the same
@rdblue  had thoughts  on how to expose such an API in #315
 

> @prodeezy & @rdsr, I think this could be exposed using Spark's multi-part name format, like we do with metadata tables.
> 
> For example, to read the history table you use `db.table.history`. We could do the same thing with snapshot IDs for time-travel, like `db.table.982135791981`. And we could then use `..` to denote a range, like `db.table.982135791981..7159871509310`. That would get passed to Iceberg as `Identifier(Array("db", "table", "982135791981", ""), "7159871509310")`.

**Comment by jerryshao** [comment]
Current Spark uses option `snapshot-id` to specify which snapshot to read. May be an easy way to introduce incremental scan in Spark is to use options like `start-snapshot-id`, `end-snapshot-id`.

**Comment by rdblue** [comment]
Good idea, @jerryshao!

Since this one is finished, I'm going to close it. Could you open a new issue or PR for incremental scan properties?

**Comment by jerryshao** [comment]
Sure, will do.
