### ISSUE TITLE
Convert Spark filters to IN and NOT_IN

### ISSUE THREAD

**Issue by rdblue** [apache/incubator-iceberg#748]
Now that IN and NOT_IN expressions are supported, we should update SparkFilters to convert to them instead of rewriting to a tree of OR and equality filters.

**Comment by jun-he** [comment]
@rdblue  I have created a PR to update `SparkFilters`.

**Comment by rdblue** [comment]
This was done by #749. I'm closing this. Thanks @jun-he!
