### ISSUE TITLE
Include the cost to open a file during split planning

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#77]
We need to take into account the cost to open a file to avoid straggler tasks. As an example, see how `spark.sql.files.openCostInBytes` is handled in Spark.

Let's consider a case when we have 500 files with 10 records and 50 files that contain 1000000 entries. Today, Iceberg will group all small files into one task. Consequently, opening those files will become a bottleneck. Locally, Iceberg was 2x times slower than Spark file source (w/o vectorized execution). The test was executed with 4 executors. Iceberg grouped files into 2 tasks. The task with many small files was taking most of the time. As opposed to this, Spark grouped files into 20 bins.

**Comment by rdblue** [comment]
Good idea. Any suggestion for the default open cost?

**Comment by aokolnychyi** [comment]
It seems it is better to overestimate a bit. By default, Spark sets it to 4MB. I think we can try some numbers below and above and see what performs better.

**Comment by rdblue** [comment]
Okay, let's start with 4 MB. We can update it when we have better data.

**Comment by aokolnychyi** [comment]
Once I implemented this locally, I started to wonder if we should add the opening cost to every file.

For example, we might have two Parquet files 62MB each. Rigth now, Iceberg will pack them into one bin, which is the right thing to do. If we simply add 4MB to the weight of each file, those files will be placed into separate bins. I am not sure it is a big deal, but I think having one bin is better in this case.

As our main goal is to avoid straggler tasks, we can add the cost of opening to files that are smaller than a configurable threshold. Let's say 10 MB.

Also, Spark only adds the cost of opening when a file is already assigned to a partition. For example, if we have a bin with one 62 MB file, we will still place the second file into the same bin as 62 + 4 + 62 = 128.

@rdblue @mccheah what do you think?

**Comment by rdblue** [comment]
I'm okay with either option. I think it is hard to know which one is going to be better, so I would opt for a simple solution.

I think a simple one is much like the threshold you proposed. Could we implement a minimum weight for a file? That would be easy.

**Comment by aokolnychyi** [comment]
Exactly, it is hard to estimate what would perform better as it would highly depend on a particular use case. Let's go for the min file weight. It is simple, it will prevent Iceberg from putting a huge number of files into one bin and the bin size will be closer to the target size in case of average files.

Let me submit a PR.
