### ISSUE TITLE
Integrate the Apache Flink into Apache Iceberg

### ISSUE THREAD

**Issue by openinx** [apache/incubator-iceberg#788]
@rdblue we've had some discussion about integrating the apache flink into apache iceberg,  Thanks for your helpful information. 
Here I written the background, Flink requirement and designs in the document [1], please take a look. 

Also FYI @aokolnychyi , Thanks.

[1].https://docs.google.com/document/d/1idTjQCubhOCea8LkKJ_5aMTV4V_Wf1n0aYhabGsLQZc/edit?usp=sharing

**Comment by openinx** [comment]
@aokolnychyi  How do you think about the document  ? I mean, would the flink's necessary incremental consumption and low latency violate iceberg's roadmap ? If not so, I can provide the more detailed design and make this work forward,  the iceberg would be the first data lake product which support apache flink.

**Comment by openinx** [comment]
@rdblue Thanks for your roadmap confirmation,  so the next thing to do would be how will we design and implement it.  Indeed, I didn't consider much about the s3 storage,  the readers might could not see the unclosed appending log(although it's not a problem in HDFS). it might be the biggest obstacle I guess,  the log would also introduce the coordinating issues as you said. Yeah, I have to admit that it's really not a very mature idea.  Anyway,  thanks for pointing those out and I would provide a more detailed document about the flink & iceberg integration and think about as many cases as I could. 

Thanks.

**Comment by openinx** [comment]
@rdblue @aokolnychyi  @rdsr I've shared a [document](https://docs.google.com/document/d/1GmPM2R-ZRF4MDnHUlMAYegr-_NEm2Hz9okq6P13_ffQ/edit?usp=sharing) about the flink integration work,  please take a look, thanks in advance.

**Comment by aokolnychyi** [comment]
@openinx, sorry for the late reply. I think the Iceberg community would love to have a public Flink integration and use cases with a reasonably low latency should be properly supported. I went through the docs and saw a lot of great discussion. I am also glad that Netflix shared their implementation as an example. I'll need to go though that.

**Comment by openinx** [comment]
Currently, @waterlx is working on the code integration, the progress is here. https://github.com/apache/incubator-iceberg/issues/567.  FYI @aokolnychyi

**Comment by openinx** [comment]
All the process are tracked in issue #567 , let's close this issue.
