### ISSUE TITLE
Update iceberg-spark to use Hive tables

### ISSUE THREAD

**Issue by rdblue** [apache/incubator-iceberg#8]
The Spark integration currently uses path-based tables and the `HadoopTables` implementation. Now that iceberg-hive is available, Spark should support named tables loaded with `HiveTables`.

**Comment by aokolnychyi** [comment]
@rdblue How do you see it in 2.4? I understand that `HiveTables` will be used when no path is given but how will we fetch the table identifier? As another data source property?

Also, how will it look like when we have support for `CREATE TABLE` statements, where `LOCATION` says if it is a managed or external table?

**Comment by rdblue** [comment]
I was planning on adding support by inspecting the path. If it contains `/`, then it is a path and should use HadoopTables. If it doesn't, then use it as a table identifier with HiveTables.

**Comment by aokolnychyi** [comment]
@rdblue Have you already started working on this? If not, we can contribute this part if it doesn't depend on the catalog effort.
