### ISSUE TITLE
HadoopTables vs HadoopCatalog

### ISSUE THREAD

**Issue by rdsr** [apache/incubator-iceberg#820]
Today we have both these APIs to work with HDFS tables.  It seems all functionality of HadoopTables  is supported by HadoopCatalog, with one exception. HadoopCatalog expects all its tables under a common root dir.  @aokolnychyi , @rdblue , what do u think. Should should we replace usage of `HadoopTables` with `HadoopCatalog` and remove `HadoopTables` and its parent interface `Tables`?

**Comment by jerryshao** [comment]
I think these are two different scenarios, especially in Spark. Catalog (both hadoop and hive catalog) can be plugged into Spark's multi-catalog interface, which will benefit the SQL scenario, as well as DataFrame of course; whereas `HadoopTables` I think the main scenario is DataFrame API, where we don't require a catalog necessarily.

**Comment by xabriel** [comment]
Agree that they are two different use cases.

In our use case, we have a decoupled Catalog that has minimal knowledge about Iceberg. Thus we use the `HadoopTables` implementation.

**Comment by rdsr** [comment]
This makes sense to me. I'll close this ticket. Thks everyone!
