### ISSUE TITLE
Add file_type to DataFile structure 

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/incubator-iceberg#824]
Per the merge on read design doc: https://docs.google.com/document/d/1FMKh_SQ6xSUUmoCA8LerTkzIxDUN5JbStQp5Hzot4eo/edit, In order to support row-level delete, we need to add a deletion type to DataFile structure.

**Comment by chenjunjiedada** [comment]
@openinx FYI, Just change the title for naming since the deletion file is a data file too, so using `file_type` would be more clear.  

And it should be defined as optional since there may be existing data files in the table. The actual stored value of `file_type` could be:

- null: normal data file that has the defined table schema,
- 0: normal data file that has the defined table schema, the default 
- 1: file and position based deletion data file that has the schema (_file, _pos)
- 2: column equality-based deletion data file that has the schema(_filed_id, _value)

The read value should be (0, 1, 2), though.

**Comment by openinx** [comment]
+1

**Comment by chenjunjiedada** [comment]
This is resolved by https://github.com/apache/incubator-iceberg/pull/1030.
