### ISSUE TITLE
Make Iceberg support case insensitivity

### ISSUE THREAD

**Issue by xabriel** [apache/incubator-iceberg#83]
Iceberg's current implementation has column case sensitivity, which hinders usability, as most sql users expect case insensitivity by default. While a query like the following will succeed in other Spark Readers, it will fail on Iceberg:

```sql
SELECT COUNT(*)
FROM iceTable
WHERE year = 2017
  AND MONTH = 11 -- Notice how MONTH has different casing than other predicates
  AND day = 01
```

This will fail with a stack trace similar to:
```
com.google.common.util.concurrent.UncheckedExecutionException: com.netflix.iceberg.exceptions.ValidationException: Cannot find field 'MONTH' in struct: struct<...>
...
```

PR to solve this issue at `iceberg-api` level: https://github.com/apache/incubator-iceberg/pull/82

More PRs to use this new flag to follow.

**Comment by xabriel** [comment]
PR #82 solves this issue at `iceberg-api` level.

We still need follow up PRs to:

1) Expose this new `caseSensitive` flag as a configuration, perhaps by introducing the use of `org.apache.hadoop.conf.Configuration`.
2) Also need to address a comment from @rdblue on #83:
>  I think some of these Evaluators will also need case sensitivity options. It doesn't do much good to support it in expression binding if it isn't also exposed when working with expressions in other ways. Can you also open a follow-up issue?

**Comment by xabriel** [comment]
PR #89, just merged, solves this problem all the way to the Spark Reader.

Jotting here some minor follow up items so that we don't forget:

Need to address comments:
https://github.com/apache/incubator-iceberg/pull/89#discussion_r266684786
and
https://github.com/apache/incubator-iceberg/pull/89#discussion_r266685152

**Comment by xabriel** [comment]
There's another issue with `Filterable`s described in #145 .

**Comment by rdblue** [comment]
I'm going to close this because #89 and #141 fixed the original problem. #145 would be nice to fix, but the code works as it is right now.
