### ISSUE TITLE
Does iceberg support copy on write or merge on read?

### ISSUE THREAD

**Issue by yiguolei** [apache/incubator-iceberg#860]

**Comment by openinx** [comment]
@yiguolei , I think you may want to read this message :-)  https://lists.apache.org/thread.html/r9ad6fccf6bdeb48b5471ba079271163c7cdb2a9bda810bfa3fdb84a4%40%3Cdev.iceberg.apache.org%3E

**Comment by rdblue** [comment]
Iceberg has support for implementing copy-on-write right now and we are working on formats for row-level delete that use a merge-on-read approach.
