### ISSUE TITLE
HadoopTableOperations.commit is not an atomic operation

### ISSUE THREAD

**Issue by emerson-zhao** [apache/incubator-iceberg#864]
When distributed concurrent commits, renameToFinal and writeVersionHint are not guaranteed in an atomic operation，an older version may be stored in version-hint .

**Comment by aokolnychyi** [comment]
I think `version-hint` is just a hint. The rename operation is the actual atomic commit. Whenever Iceberg refreshes a table, it uses the version in `version-hint` as a starting point and tries to find any new versions.

**Comment by rdblue** [comment]
Hadoop tables use an atomic rename to commit metadata. That is atomic as long as the file system supports it.

The version hint is just a hint. You can recover the actual state by making a series of `exists` calls without it. Because it is a hint, it doesn't matter if it is up to date.
