### ISSUE TITLE
Remove VTTS

### ISSUE THREAD

**Issue by waterlx** [apache/incubator-iceberg#869]
VTTS (Valid Through TimeStamp) is specific to Netflix

**Comment by rdblue** [comment]
It is valid-through timestamp.

**Comment by stevenzwu** [comment]
we should totally remove VTTS. but I do find the `low` and `high` watermark/timestamp metadata useful. I am actually thinking about adding  another `avg` watermark/timestamp to help us publish end-to-end latency (min, max, avg) after commit is successful.

**Comment by waterlx** [comment]
VTTS is removed literally but all "watermark"  related logic is kept as they are.

**Comment by waterlx** [comment]
@stevenzwu Got your idea.
