### ISSUE TITLE
Use Iceberg generic record to replace Avro IndexedRecord and add a translation to/from data type in Flink

### ISSUE THREAD

**Issue by waterlx** [apache/incubator-iceberg#870]
Current implementation uses Avro as the intermediate fomat, as:
`Input as Java Map, serialized to Avro IndexRecord (as the intermediate format), then call Parquet.write(Iceberg API) to write into Parquet file.`

1. We need to remove that dependency and use Iceberg generic record/built-in types (maps with non-string keys, decimals, date/time types...) as the input
- Remove AvroSerializer and its implementations
- Remove AvroUtils
- Remove the setting on serializer in IcebergSinkAppender

2. Add the translation to/from Flink native formats (like we did for InternalRow for Spark)

3. FileWriter#write() could accept convention type in addition to Iceberg generic record. See [this comment](https://github.com/apache/incubator-iceberg/pull/856#discussion_r396796302).

**Comment by stevenzwu** [comment]
I 100% agree that we need to support Iceberg GenericRecord or Flink native formats. We probably need some generic serializer interface. We use Avro quite extensively in the streaming pipeline. It would be nice if we can avoid the format conversion and write Avro directly.

**Comment by waterlx** [comment]
@stevenzwu Thanks for the comments and sorry for my late response~~

Regarding:
> We probably need some generic serializer interface.

Yes, I rename "AvroSerializer" into "RecordSerializer" as the generic serializer interface to transform from any input format to Iceberg **Record**

Regarding: 
> We use Avro quite extensively in the streaming pipeline. It would be nice if we can avoid the format conversion and write Avro directly

Got your idea. Opened a new issue as https://github.com/apache/incubator-iceberg/issues/943

**Comment by waterlx** [comment]
Ready to close this issue as Avro and IndexedRecord are removed, by the folllowing commits:
- https://github.com/apache/incubator-iceberg/pull/856/commits/7ed7583fca49252abdcd587716fc6e3de5c55423
- https://github.com/apache/incubator-iceberg/pull/856/commits/01f66bac827407f5fbcc6ef1d8f37b042dc9de8a
