### ISSUE TITLE
Any easier/beginner friendly issues I can work on?

### ISSUE THREAD

**Issue by nikshepsvn** [apache/incubator-iceberg#902]
Hi all, I'm a university student who has a little too much free time during the quarantine and thought I'd help out with the project. I would really appreciate if someone could point me towards some easier issues/resources I can start with to build familiarity with how everything works!

some context: I've interned on data teams previously and definitely think this project will do a lot to fix some common problems data teams face, I haven't worked too much with Java but I'm very eager to dive in and learn/help as much as I can! Oh, and I have a decent bit of experience with Python, so if there is any work that touches python code I'd love to lend a hand!

**Comment by prodeezy** [comment]
@nikshepsvn Welcome to the community. I'm just a contributor myself so take my advise as coming from that capacity and nothing more :-)

My two cents,
To familiarize yourself I'd suggest starting with going through the spec [0] and the api [1]. Python related resources are here [2].

In general, adding tests is a good way to start with both familiarizing yourself and adding value without requiring much guidance. If you find a bug while testing put up an issue with your test as illustration and maybe put a corresponding PR up.

Another good way to contribute is documentation. If you see gaps in the documentation, you can put up a PR on the docs as well. Docs are part of the code [3].

Higher level milestones are tracked here [4]. Related discussions and docs on those milestones can be found on the dev@iceberg.apache.org mailing list archives.

Having said all that, nothing precludes you from participating in discussions on issues or design docs. A fresh perspective is always welcome :-) 

Hope this helps and Good luck!

[0] - http://iceberg.incubator.apache.org/spec/ 
[1] - http://iceberg.incubator.apache.org/api-quickstart/
[2] - http://iceberg.incubator.apache.org/python-quickstart
[3] - https://github.com/apache/incubator-iceberg/tree/master/site/docs
[4] -  https://github.com/apache/incubator-iceberg/milestones

**Comment by rdblue** [comment]
I think #837 might be a good starter issue to tackle.

Avro doesn't keep track of column-level stats, so we can't currently do additional filtering on Avro files. To enable that filtering, we need to build a pass-through `FileAppender` that inspects records and keeps track of null count, total value count, lower bound, upper bound, and count of NaN values.

Doing this for Avro generics is a good place to start, then moving on to get stats for Spark InternalRow.

**Comment by rdblue** [comment]
I'm going to close this since we don't need to track it as an issue.
