### ISSUE TITLE
Use null-safe locations in metadata tables

### ISSUE THREAD

**Issue by aokolnychyi** [apache/incubator-iceberg#904]
Right now, different metadata tables have different logic in `location()`. I think it makes to standardize and ensure we use only null-safe locations. For example, `ops.current().location()` seems a good candidate. Currently, we can hit a NPE when querying metadata tables.

**Comment by nikshepsvn** [comment]
Hey Anton! I'd love to help with this (: Would you mind pointing me at some resources/giving me some context so I can get started?

**Comment by aokolnychyi** [comment]
@nikshepsvn, that'd great. Seems like @shawnding has a change already. @shawnding, could you confirm?

@nikshepsvn, feel free to pick any other issue that you feel comfortable with.
