### ISSUE TITLE
Document Java version should be exact 1.8

### ISSUE THREAD

**Issue by TisonKun** [apache/incubator-iceberg#915]
https://github.com/apache/incubator-iceberg/blob/720b240a3e6a32b6f01173ebcc448c2c6e32e13a/build.gradle#L43-L44

https://github.com/apache/incubator-iceberg/blob/720b240a3e6a32b6f01173ebcc448c2c6e32e13a/build.gradle#L82-L83

When I build with Java 13 environment it fails. We should document it at least in `README.md`.

**Comment by rdblue** [comment]
Sounds good. Could you open a PR?

**Comment by TisonKun** [comment]
@rdblue Yep. I will open a PR a bit later.

**Comment by TisonKun** [comment]
Hi @rdblue I've created a PR. Could you have a look?
