### ISSUE TITLE
Support for AWS Glue as an alternative Hive metastore implementation

### ISSUE THREAD

**Issue by yujiantao** [apache/incubator-iceberg#932]
It is an old issue from https://github.com/Netflix/iceberg/issues/112.
Do we have any plan/progress on this?

**Comment by rdblue** [comment]
Glue doesn't support Hive table locking, so there is no atomic operation we can use for the metadata update. If that's changed, then we would gladly add a Glue metastore. I recommend talking to your AWS point of contact if you want this.

**Comment by yujiantao** [comment]
@rdblue Got it, thanks!
