### ISSUE TITLE
SnapshotpId() in SnapshotProducer is invalid in certain cases

### ISSUE THREAD

**Issue by rdsr** [apache/incubator-iceberg#956]
E.g with cherrypick or rollback. The snapshotId() does not reflect the snapshot which is to be committed.  The PR #955 reflects that bug. Many testcases related to cherrypick/rollback fail.

This was discovered when working on #939

**Comment by prodeezy** [comment]
@rdsr  is there a sample gist or way I can reproduce this issue?

**Comment by prodeezy** [comment]
Nvm, i see your explanation in https://github.com/apache/incubator-iceberg/pull/955

**Comment by rdblue** [comment]
Should we close this because we aren't going to fix it?

**Comment by rdsr** [comment]
+1
