### ISSUE TITLE
TimestampType support in GenericParquetReaders/GenericParquetWriter is different

### ISSUE THREAD

**Issue by vanliu-tx** [apache/incubator-iceberg#969]
GenericParquetReaders support TimestampType with zone and without zone.

![image](https://user-images.githubusercontent.com/64360028/80307923-c1239900-87fe-11ea-807c-f1aedb46555e.png)

GenericParquetWriter only support Timestamp with zone.

![image](https://user-images.githubusercontent.com/64360028/80307930-d0a2e200-87fe-11ea-9aa4-cb58d010488c.png)

**Comment by chenjunjiedada** [comment]
@vanliu-tx , There is a PR: https://github.com/apache/incubator-iceberg/pull/891 for this. Also, we are using `SparkParquetReader` and `SparkParquetWriter` for spark engine.

**Comment by vanliu-tx** [comment]
@chenjunjiedada in my case we don't use any engine to read/write iceberg table, we want to minimize the resource used.

**Comment by chenjunjiedada** [comment]
@vanliu-tx , Does PR: https://github.com/apache/incubator-iceberg/pull/891 works for you? I think that fixes the issue.

**Comment by waterlx** [comment]
> in my case we don't use any engine to read/write iceberg table, we want to minimize the resource used.

@vanliu-tx If you need an engine-independent fix, would you please take a look at #965 ? It is dedicated to address your issue so it is shorter than #891.
But I might need to know your Parquet version. Both of #965 and #891 depend on Parquet 1.11, with "logical type annotation". Based on that, we could build a flag which helps to distingish between timestamp with and without zone. In Parquet 1.10, I could not find a flag like that yet. 
Please let me know if it works for you.

**Comment by waterlx** [comment]
This issue is a dup of #965 or #475. All of them would be addressed by #891 thoroughly

**Comment by vanliu-tx** [comment]
ok, close it as duplicate with https://github.com/apache/incubator-iceberg/pull/965
