### ISSUE TITLE
Transform.day does not produce DateType value

### ISSUE THREAD

**Issue by chenjunjiedada** [apache/incubator-iceberg#984]
Transform.day was expected to produce date type, see: https://github.com/apache/incubator-iceberg/issues/279. It does produce the date type but not date value. Actually it produces the integer value. I think we should add a real date transform `Transform<T, DateType>`.

**Comment by rdblue** [comment]
`Transform.day` produces the internal value for a date, the number of days from the unix epoch. Iceberg uses that representation, not a Java date type.
